### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by Programmer-Timmy** [dave-lang/webmin-docker#12]
**Describe the bug**
when opening the module i get this error:
 500 -
Can't locate docker-lib.pl in @INC (@INC contains: /usr/share/webmin /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl) at /usr/share/webmin/docker/index.cgi line 6.

**Versions (please complete the following information):**
 - OS: Ubuntu Linux 22.04.4
  - Webmin version: 2.202
 - Module Version: 0.5.0

**Additional context**
I'm prety new to this. but docker is running corectly

**Comment by dave-lang** [comment]
Apologies, missed this one.

That looks like a partial installation of the module, missing some of the files. Did you install it via the instructions or a custom build?

**Comment by Programmer-Timmy** [comment]
Via the url didn't work for me. So, I downloaded the file from the github release page and did it like that.

**Comment by dave-lang** [comment]
I'll reconfigure my test system and try it that way - maybe it was a corrupt download?

https://github.com/dave-lang/webmin-docker/releases/download/0.5.0/docker.wbm.gz should work

**Comment by Programmer-Timmy** [comment]
![image](https://github.com/user-attachments/assets/1819af85-8cc0-42f6-aada-7627b2770d08)

I tried reinstalling it, but the issue remains. The file is there.

**Comment by dave-lang** [comment]
I've tried to reproduce - so far it's only by adding the module to the file system manually and with incorrect permissions I see this. If you installed via the webmin module page that should set it up correctly

**Comment by Programmer-Timmy** [comment]
I wil try it on a other system. Ill let you know

**Comment by Lulech23** [comment]
This is occurring for me as well under the same context:

- OS: Ubuntu Linux 22.04.4
- Webmin version: 2.202
- Module Version: 0.5.0

Both the URL suggested in the readme and the package under releases present the same error. It appears that the default search path for required files does not include the working directory.

I had to change line 6 of index.cgi from `require 'docker-lib.pl';` to `require './docker-lib.pl';`, but there may be a deeper solution.

**Comment by Programmer-Timmy** [comment]
I implemented the change, and it works! Thanks!

**Comment by dave-lang** [comment]
Thanks for figuring it out, strangely my env is identical webmin-wise. I'll get a new release out shortly
