### ISSUE TITLE
Live Console And Send Messages

### ISSUE THREAD

**Issue by JustablockCode** [dave-lang/webmin-docker#13]
Hi, I have 2 ideas for your project.

Idea 1:
Live Console. Make a console that displays the live output.

Idea 2:
Commands. Make so you can send commands to the container.

Oh and also please make a button to clear the log easily.

Hope you will like these ideas.

**Comment by dave-lang** [comment]
By live console do you mean the container logs? I'd considered it and can look into a basic auto-refreshing viewer similar to webmins log viewer.

For commands, given all the potential permutations and interactive nature of some commands, I would recommend using [webmin's terminal](https://webmin.com/docs/modules/terminal/), https://www.portainer.io or https://yacht.sh

**Comment by dave-lang** [comment]
Auto refresh and filtering of logs added in https://github.com/dave-lang/webmin-docker/releases/tag/1.0.0

**Comment by dave-lang** [comment]
Auto refresh and filtering of logs added in https://github.com/dave-lang/webmin-docker/releases/tag/1.0.0
