### ISSUE TITLE
Failed to install module : Not a valid Perl module

### ISSUE THREAD

**Issue by webnoob** [dave-lang/webmin-docker#17]
**Describe the bug**
I install via the HTTP url method and get this error:

![image](https://github.com/user-attachments/assets/7f40b684-1bbb-4013-9f43-e3ddf76fcd1d)

**To Reproduce**
1. Go to 'Perl Modules'
2. Click on 'HTTP URL radio'
3. Paste in latest link: https://github.com/dave-lang/webmin-docker/releases/latest/download/docker.wbm.gz

**Expected behavior**
It to install :)

**Screenshots**

**Versions (please complete the following information):**
Webmin version: 2.202 (latest installed today)

**Additional context**
I've also tried the previous release URL as well.

**Comment by dave-lang** [comment]
You need to install it as a Webmin module - it's under Webmin, Webmin Configuration, Webmin Modules
https://webmin.com/docs/modules/webmin-configuration/#installing

**Comment by webnoob** [comment]
Apologies for this. Completely missed there was another module section 🤦‍♂️
