### ISSUE TITLE
not finishing the installation

### ISSUE THREAD

**Issue by PauloBoaventura** [dave-lang/webmin-docker#3]
This section gives an error, not finishing the installation...

`
# Install Webmin
RUN echo root:password | chpasswd && \
    echo "Acquire::GzipIndexes \"false\"; Acquire::CompressionTypes::Order:: \"gz\";" >/etc/apt/apt.conf.d/docker-gzip-indexes && \
    update-locale LANG=C.UTF-8 && \
    echo deb https://download.webmin.com/download/repository sarge contrib >> /etc/apt/sources.list && \
    wget http://www.webmin.com/jcameron-key.asc && \
    apt-key add jcameron-key.asc && \
    apt-get update && \
    apt-get install -y webmin && \
    apt-get clean && \
    echo "$(cat /etc/webmin/webmin.acl) docker" > /etc/webmin/webmin.acl`

**Comment by RandomBotTech** [comment]
I have the same problem. I am ubuntu server 20.04.6. Webmin and docker are installed and working well. Anyone have a solution?

**Comment by dave-lang** [comment]
What is the error you get during install. Ive done multiple installs using the url option and the release package.

The latest one is
https://github.com/dave-lang/webmin-docker/releases/download/0.4.0/docker.wbm.gz.

**Comment by AzhamProdLive** [comment]
> What is the error you get during install. Ive done multiple installs using the url option and the release package.
> 
> The latest one is https://github.com/dave-lang/webmin-docker/releases/download/0.4.0/docker.wbm.gz.
> 
> Try using either the file upload or Http URL method from https://webmin.com/docs/modules/webmin-configuration/#installing

I have tried to install the module too, and the error I get is "Not a vaild Perl module"

The logs : 
```
Downloading https://github.com/dave-lang/webmin-docker/releases/download/0.4.2/docker.wbm.gz ..
Downloading https://objects.githubusercontent.com/github-production-release-asset-2e65be/661591323/cd631556-def8-4e2b-b899-48a4d04ab290?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240602%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240602T203006Z&X-Amz-Expires=300&X-Amz-Signature=647e70e104857e6e4d1701edc53bd781634c80a4aa29b578724a00420e04500c&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=661591323&response-content-disposition=attachment%3B%20filename%3Ddocker.wbm.gz&response-content-type=application%2Foctet-stream (3.32 KiB) ..
     Received 1 KiB (30 %)
     Received 1.34 KiB (40 %)
     Received 2.34 KiB (70 %)
     Received 2.69 KiB (80 %)
     Received 3.32 KiB (100 %)
.. download complete.

Failed to install module : Not a valid Perl module
```

**Comment by dave-lang** [comment]
Thanks for at confirming the install works :)

I'm going to close this - the docker script works for testing & the install package seems to be fine.
