### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by Lawkss** [dave-lang/webmin-docker#5]
Thanks for the module! 

I have some suggestions: 

Change the module name to include capital letters? all other webmin modules have the second word as capital.

So

`Docker container management `

to

`Docker Container Management`

or I would prefer just: 

`Docker Containers
`

it would also be cool to get the icon checks for the status like for server dashboard:

![Screenshot 2024-05-20 174417](https://github.com/dave-lang/webmin-docker/assets/50915914/a606e2a7-37e6-44cf-a633-90990a56f048)

**Comment by dave-lang** [comment]
Good suggestions

I've just made the naming change and there's a minor release up. I'll look at doing the icons in the next day or two
