### ISSUE TITLE
UI buttons not scaling properly

### ISSUE THREAD

**Issue by pietru2004** [dave-lang/webmin-docker#9]
**Describe the bug**
![obraz](https://github.com/user-attachments/assets/193e9fee-7d6f-4989-89b7-001e67f1e30f)
I noticed that text buttons such as Start and Stop don't scale properly. Also could they have button look?

example classes
```
    <style>
        .btn1:link, .btn1:visited {
            background-color: white;
            color: black;
            border: 2px solid rgb(30, 174, 210);
            padding: 5px 10px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
        }
        
        .btn1:hover, .btn1:active {
            background-color: rgb(20, 122, 148);
            color: white;
        }

        .btn2:link, .btn2:visited {
            background-color: white;
            color: black;
            border: 2px solid rgb(30, 114, 210);
            padding: 5px 10px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
        }
        
        .btn2:hover, .btn2:active {
            background-color: rgb(24, 92, 170);
            color: white;
        }
    </style>
```

**Comment by dave-lang** [comment]
I've had a look into it again as I previously tried to implement consistent buttons. There still doesn't appear to be a good cross-theme supported method that doesn't break the layout or have odd side effects.

I've instead adjusted the layout to handle smaller displays better within the limits of Webmin's framework - this is an English example at 1240px wide. Unfortunately Polish is more verbose, so it won't be as nice:
![image](https://github.com/user-attachments/assets/bffd5093-844b-4c76-8cbd-4dd6c2782d1d)

Prior to update:
![image](https://github.com/user-attachments/assets/22e043d2-a5c0-4c70-ba7b-090c73be3fe6)

**Comment by pietru2004** [comment]
@dave-lang what if buttons for start stop and etc. were placed under container name ?
like in second row
![obraz](https://github.com/user-attachments/assets/6279baa3-5ac8-4ebc-bac2-fc39a0999c74)

**Comment by dave-lang** [comment]
I think I've managed to get something reasonable across all screen sizes. I've switched to Polish as it's more verbose. Want to avoid double lines as it makes it harder to scan longer lists.

Phone:
![image](https://github.com/user-attachments/assets/a4d8ba6f-4c60-44a5-8725-ea19f454bd29)

768px
![image](https://github.com/user-attachments/assets/c5e7cb30-ea0e-44fa-ac80-e10cfacd5302)

1024px
![image](https://github.com/user-attachments/assets/e3bbb92b-1c30-4453-be4c-1c68461244a6)

1280px
![image](https://github.com/user-attachments/assets/07c8427d-445f-489d-8d53-6a6b7409657e)

2560px
![image](https://github.com/user-attachments/assets/cb9c674e-6dca-4dca-a90e-f385e03db7ed)
